version: "3.7"

services:
  nodejs:
    image: davevronay/wtfserver
    container_name: nodejs
    restart: always
    ports:
      - 4000:4000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Andrea1971!
      MYSQL_DB: wtfdata
    networks:
      - app-network
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes: 
      - wtf-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Andrea1971!
      MYSQL_DATABASE: wtfdata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: 
  wtf-mysql-data: