version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install --production && node ./index.js"
    ports:
      - 4000:4000
    working_dir: /wtfserver
    volumes: 
      - ./:/wtfserver
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: wtfdata
      
  mysql:
    image: mysql:5.7
    volumes: 
    - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wtfdata

volumes: 
  todo-mysql-data:MYSQ