apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Dev\kubernetes\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    io.kompose.service: nodejs
status:
  loadBalancer: {}
