apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Dev\kubernetes\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Dev\kubernetes\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: nodejs
    spec:
      containers:
      - env:
        - name: MYSQL_DB
          value: wtfdata
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: Andrea1971!
        - name: MYSQL_USER
          value: root
        image: davevronay/wtfserver
        imagePullPolicy: ""
        name: nodejs
        ports:
        - containerPort: 4000
        resources: {}
      initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql:3306; do echo waiting for db; sleep 2; done;']
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
